#!/bin/sh
################################################################################
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.tv; see the file COPYING.  If not, write to
#  the Free Software Foundation, 51 Franklin Street, Suite 500, Boston, MA 02110, USA.
#  http://www.gnu.org/copyleft/gpl.html
################################################################################

# remove old ljalves files
echo "removing old sources ..."
rm -rf ljalves
rm -rf ljalves-*

################################################################################

# media_build dl
echo "getting media_build sources ..."
  if [ ! -d media_build.git ]; then
    git clone https://github.com/ljalves/media_build.git ljalves/media_build
  fi

echo "cleaning media_build sources ..."
  rm -rf ljalves/media_build/.git

################################################################################

# ljalves tbs drivers dl
echo "getting ljalves sources ... !!! huge !!!"
  if [ ! -d linux_media.git ]; then
    git clone --depth=1 https://github.com/ljalves/linux_media.git -b latest ljalves/media
  fi

  cd ljalves/media
    git pull
    GIT_REV=`git log -n1 --pretty=format:"%ad" --date=short`

# remove unnessecary files
  rm -rf Documentation
  cd ../..

echo "copying ljalves sources ..."
  rm -rf ljalves-$GIT_REV
  cp -R ljalves ljalves-$GIT_REV

echo "cleaning ljalves sources ..."
  rm -rf ljalves-$GIT_REV/media/.git

################################################################################

echo "packing sources ..."
tar cvJf ljalves-$GIT_REV.tar.xz ljalves-$GIT_REV

echo "remove temporary sourcedir ..."
  rm -rf ljalves-$GIT_REV
  rm -rf ljalves
