#!/bin/sh
################################################################################
#      This file is part of OpenELEC - http://www.openelec.tv
#      Copyright (C) 2009-2012 Stephan Raue (stephan@openelec.tv)
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.tv; see the file COPYING.  If not, write to
#  the Free Software Foundation, 51 Franklin Street, Suite 500, Boston, MA 02110, USA.
#  http://www.gnu.org/copyleft/gpl.html
################################################################################

echo "getting sources..."
  cvs -z3 -d:pserver:anonymous@dvbhdhomerun.cvs.sourceforge.net:/cvsroot/dvbhdhomerun co -P dvbhdhomerun

CVS_DATE=$(date "+%Y%m%d")

echo "copying sources..."
  rm -rf dvbhdhomerun-*
  cp -R dvbhdhomerun dvbhdhomerun-$CVS_DATE

echo "cleaning sources..."
  find dvbhdhomerun-$CVS_DATE -name CVS -exec rm -rf {} ";"
  rm -fr dvbhdhomerun-$CVS_DATE/.cvsignore dvbhdhomerun-$CVS_DATE/debian

echo "packing sources..."
  tar cvjf dvbhdhomerun-$CVS_DATE.tar.bz2 dvbhdhomerun-$CVS_DATE

echo "remove temporary sourcedir..."
  rm -rf dvbhdhomerun dvbhdhomerun-$CVS_DATE
