#!/bin/sh
################################################################################
#      This file is part of OpenELEC - http://www.openelec.tv
#      Copyright (C) 2009-2012 Stephan Raue (stephan@openelec.tv)
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.tv; see the file COPYING.  If not, write to
#  the Free Software Foundation, 51 Franklin Street, Suite 500, Boston, MA 02110, USA.
#  http://www.gnu.org/copyleft/gpl.html
################################################################################

PKG_NAME="libshairplay"
PKG_VERSION=""
GIT_REPO="https://github.com/juhovh/shairplay.git"
DEST_DIR="$PKG_NAME"

echo "getting sources..."
  if [ ! -d $DEST_DIR-latest ]; then
    git clone $GIT_REPO $DEST_DIR-latest
  fi

  cd $DEST_DIR-latest

echo "getting current version..."
  GIT_OLD_REV=`git log -n1 --format=%h`
  echo $GIT_OLD_REV

echo "updating with latest from head..."
    git pull

echo "getting version..."
  GIT_REV=`git log -n1 --format=%h`
  echo $GIT_REV
  cd ..

  PKG_VERSION="$GIT_REV"

echo "copying sources..."
  rm -rf $PKG_NAME-$PKG_VERSION
  cp -R $DEST_DIR-latest $PKG_NAME-$PKG_VERSION
  echo "$GIT_REV" > $PKG_NAME-$PKG_VERSION/git.version

echo "cleaning sources..."
  rm -rf $PKG_NAME-$PKG_VERSION/.git

echo "packing sources..."
  tar cvJf $PKG_NAME-$PKG_VERSION.tar.xz $PKG_NAME-$PKG_VERSION

echo "remove temporary sourcedir..."
  rm -rf $PKG_NAME-$PKG_VERSION

echo "copying tar balls to sources..."
  mkdir -p ../../sources/$PKG_NAME/

  mv $PKG_NAME-$PKG_VERSION.tar.xz ../../sources/$PKG_NAME/

echo "generate md5 and url files..."
  cd ../..

  md5sum sources/$PKG_NAME/$PKG_NAME-$PKG_VERSION.tar.xz > \
         sources/$PKG_NAME/$PKG_NAME-$PKG_VERSION.tar.xz.md5

  echo " http://sources.openelec.tv/devel/$PKG_NAME-$PKG_VERSION.tar.xz" > \
         sources/$PKG_NAME/$PKG_NAME-$PKG_VERSION.tar.xz.url

echo "Update meta files and rename patches..."

  if [ $PKG_VERSION != $GIT_OLD_REV ] ; then
    sed -i "s/PKG_VERSION=\"$GIT_OLD_REV\"/PKG_VERSION=\"$PKG_VERSION\"/" packages/multimedia/$PKG_NAME/meta

    cd packages/multimedia/$PKG_NAME/patches
    mv $GIT_OLD_REV $PKG_VERSION
  fi

echo "Source tar balls generated for $PKG_NAME NEW PKG_VERSION=$PKG_VERSION and OLD PKG_VERSION=$GIT_OLD_REV successfully."

