#!/bin/sh
################################################################################
#      This file is part of OpenELEC - http://www.openelec.tv
#      Copyright (C) 2009-2013 Stephan Raue (stephan@openelec.tv)
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.tv; see the file COPYING.  If not, write to
#  the Free Software Foundation, 51 Franklin Street, Suite 500, Boston, MA 02110, USA.
#  http://www.gnu.org/copyleft/gpl.html
################################################################################

PKG_NAME=media_build
HG_URL=http://linuxtv.org/hg/~endriss/
HG_NAME=media_build_experimental
HG_REV=latest

echo "getting sources..."
  if [ ! -d $PKG_NAME.hg ]; then
    hg clone ${HG_URL}${HG_NAME} $PKG_NAME.hg
  fi

  cd $PKG_NAME.hg
    make download
    make untar
    if [ $HG_REV = latest ]; then
      hg update
      HG_REV=$(hg identify -n)
    else
      hg update $HG_REV
    fi
    # remove .hg folders
    find . -type d -name ".hg" -exec rm -fr {} \;
    cd ..

echo "copying sources..."
  rm -rf $PKG_NAME-$HG_REV
  cp -R $PKG_NAME.hg $PKG_NAME-$HG_REV

echo "cleaning sources..."
  rm -rf $PKG_NAME-$HG_REV/.hg

echo "packing sources..."
  tar cvJf $PKG_NAME-$HG_REV.tar.xz $PKG_NAME-$HG_REV

echo "remove temporary sourcedir..."
#  rm -rf $PKG_NAME-$HG_REV
