#!/bin/sh

################################################################################
#      This file is part of OpenELEC - http://www.openelec.tv
#      Copyright (C) 2009-2012 Stephan Raue (stephan@openelec.tv)
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.tv; see the file COPYING.  If not, write to
#  the Free Software Foundation, 51 Franklin Street, Suite 500, Boston, MA 02110, USA.
#  http://www.gnu.org/copyleft/gpl.html
################################################################################

. config/options $1

if [ -z "$3" ]; then
  echo "usage: $0 package_name file_pattern target_dir"
  exit 1
fi

[ -z "$PKG_URL" ] && exit 1
[ ! -d "$SOURCES/$1" -o ! -d "$3" ] && exit 1

PKG_URL_PROTO=$(echo $PKG_URL | sed -n 's|\([^,]*\),.*$|\1|p')   # get proto
case $PKG_URL_PROTO in
  git|svn)
    PKG_URL="$PKG_NAME-$PKG_VERSION.tar.xz"
    FILE="$PKG_URL"
    f="$SOURCES/$1/$FILE"
    ;;
  file)
    PKG_URL=$(echo $PKG_URL | sed -n 's|\([^,]*\),\(.*\)$|\2|p')   # get file
    PKG_URL=${PKG_URL// /_spc_}     # replace spaces
    eval PKG_URL=${PKG_URL}         # put spaces back
    PKG_URL=${PKG_URL//_spc_/ }
    FILE="$(basename $PKG_URL)"
    f="$PKG_URL"
    ;;
  *)
    FILE="$(basename $PKG_URL)"
    f="$SOURCES/$1/$FILE"
    ;;
esac

case $FILE in
$2)
  if [ ! -f $f ]; then
    echo "error: File $FILE doesn't exists in package $1 sources directory"
    echo "have you called scripts/extract before scripts/get ?"
    exit 1
  fi
  case $FILE in
    *.tar)
      tar xf $f -C $3
      ;;
    *.tar.bz2 | *.tbz)
      tar xjf $f -C $3
      ;;
    *.tar.gz | *.tgz)
      tar xzf $f -C $3
      ;;
    *.tar.xz | *.txz)
      tar xJf $f -C $3
      ;;
    *.7z)
      mkdir -p $3/$1
      7z x -o$3/$1 $f
      ;;
    *.diff | *.patch)
      cat $f | patch -d $3 -p1
      ;;
    *.diff.bz2 | *.patch.bz2 | patch-*.bz2)
      bzcat $f | patch -d $3 -p1
      ;;
    *.diff.gz | *.patch.gz | patch-*.gz)
      zcat $f | patch -d $3 -p1
      ;;
    *)
      cp -pPR $f $3
      ;;
  esac
  ;;
esac
